using Newtonsoft.Json;

namespace McpEnergyCalculator.Models;

public class McpTool
{
    [JsonProperty("name")]
    public string Name { get; set; } = string.Empty;

    [JsonProperty("description")]
    public string Description { get; set; } = string.Empty;

    [JsonProperty("inputSchema")]
    public McpToolInputSchema InputSchema { get; set; } = new();
}

public class McpToolInputSchema
{
    [JsonProperty("type")]
    public string Type { get; set; } = "object";

    [JsonProperty("properties")]
    public Dictionary<string, McpToolProperty> Properties { get; set; } = new();

    [JsonProperty("required")]
    public List<string> Required { get; set; } = new();
}

public class McpToolProperty
{
    [JsonProperty("type")]
    public string Type { get; set; } = string.Empty;

    [JsonProperty("description")]
    public string Description { get; set; } = string.Empty;

    [JsonProperty("enum")]
    public List<string>? Enum { get; set; }

    [JsonProperty("default")]
    public object? Default { get; set; }

    [JsonProperty("minimum")]
    public int? Minimum { get; set; }

    [JsonProperty("maximum")]
    public int? Maximum { get; set; }
}

public class McpToolsListRequest
{
    [JsonProperty("cursor")]
    public string? Cursor { get; set; }
}

public class McpToolsListResult
{
    [JsonProperty("tools")]
    public List<McpTool> Tools { get; set; } = new();

    [JsonProperty("nextCursor")]
    public string? NextCursor { get; set; }
}

public class McpToolCallRequest
{
    [JsonProperty("name")]
    public string Name { get; set; } = string.Empty;

    [JsonProperty("arguments")]
    public Dictionary<string, object>? Arguments { get; set; }
}

public class McpToolCallResult
{
    [JsonProperty("content")]
    public List<McpContent> Content { get; set; } = new();

    [JsonProperty("isError")]
    public bool? IsError { get; set; }
}

public class McpContent
{
    [JsonProperty("type")]
    public string Type { get; set; } = "text";

    [JsonProperty("text")]
    public string? Text { get; set; }

    [JsonProperty("data")]
    public object? Data { get; set; }

    [JsonProperty("mimeType")]
    public string? MimeType { get; set; }
}

public static class McpToolDefinitions
{
    public static List<McpTool> GetAllTools()
    {
        return new List<McpTool>
        {
            GetCalculateEnergyCostTool(),
            GetCalculateCarbonEmissionsTool(),
            GetModelInfoTool()
        };
    }

    public static McpTool GetCalculateEnergyCostTool()
    {
        return new McpTool
        {
            Name = "calculate-energy-cost",
            Description = "Calculate energy consumption and cost for LLM model invocations based on input and output tokens",
            InputSchema = new McpToolInputSchema
            {
                Properties = new Dictionary<string, McpToolProperty>
                {
                    ["model"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "The LLM model name (e.g., 'gpt-4', 'claude-3-sonnet', 'llama-2-70b')"
                    },
                    ["inputTokens"] = new McpToolProperty
                    {
                        Type = "integer",
                        Description = "Number of input tokens processed by the model",
                        Minimum = 0
                    },
                    ["outputTokens"] = new McpToolProperty
                    {
                        Type = "integer",
                        Description = "Number of output tokens generated by the model",
                        Minimum = 0
                    },
                    ["provider"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Model provider (optional, can be inferred from model name)",
                        Enum = new List<string> { "openai", "anthropic", "google", "cohere", "meta", "deepseek", "mistral", "other" }
                    },
                    ["region"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Cloud region for carbon intensity calculation (default: us-east-1)",
                        Default = "us-east-1"
                    }
                },
                Required = new List<string> { "model", "inputTokens", "outputTokens" }
            }
        };
    }

    public static McpTool GetCalculateCarbonEmissionsTool()
    {
        return new McpTool
        {
            Name = "calculate-carbon-emissions",
            Description = "Calculate carbon emissions (CO2e) for LLM model invocations based on energy consumption and regional carbon intensity",
            InputSchema = new McpToolInputSchema
            {
                Properties = new Dictionary<string, McpToolProperty>
                {
                    ["model"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "The LLM model name (e.g., 'gpt-4', 'claude-3-sonnet', 'llama-2-70b')"
                    },
                    ["inputTokens"] = new McpToolProperty
                    {
                        Type = "integer",
                        Description = "Number of input tokens processed by the model",
                        Minimum = 0
                    },
                    ["outputTokens"] = new McpToolProperty
                    {
                        Type = "integer",
                        Description = "Number of output tokens generated by the model",
                        Minimum = 0
                    },
                    ["provider"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Model provider (optional, can be inferred from model name)",
                        Enum = new List<string> { "openai", "anthropic", "google", "cohere", "meta", "deepseek", "mistral", "other" }
                    },
                    ["region"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Cloud region for carbon intensity calculation (default: us-east-1)",
                        Default = "us-east-1"
                    }
                },
                Required = new List<string> { "model", "inputTokens", "outputTokens" }
            }
        };
    }

    public static McpTool GetModelInfoTool()
    {
        return new McpTool
        {
            Name = "get-model-info",
            Description = "Get information about available LLM models, their energy consumption profiles, and supported providers",
            InputSchema = new McpToolInputSchema
            {
                Properties = new Dictionary<string, McpToolProperty>
                {
                    ["provider"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Filter by specific provider (optional)",
                        Enum = new List<string> { "openai", "anthropic", "google", "cohere", "meta", "deepseek", "mistral", "other" }
                    },
                    ["category"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Filter by model category (optional)",
                        Enum = new List<string> { "small", "medium", "large", "extra-large" }
                    },
                    ["modelName"] = new McpToolProperty
                    {
                        Type = "string",
                        Description = "Get information for a specific model (optional)"
                    }
                },
                Required = new List<string>()
            }
        };
    }
}
